name: Deploy to PyPI
on:
  push:
    branches:
      - main
jobs:
  DeployToPyPI:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set the Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install the Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - name: Append the Poetry's PATH settings to the .bashrc
        run: echo '$HOME/.poetry/bin:$PATH' >> ~/.bashrc
      - name: Apply Poetry's PATH setting
        run: source ~/.bashrc
      - name: Install dependencies
        run: poetry install
      - name: Execute the Python package build
        run: poetry run python build.py
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
